### ISSUE TITLE
how to compile DLL on OSX?

### ISSUE THREAD

**Issue by jpw** [jacobdufault/fullserializer#102]
Hi there,
Not an issue with the project at all, sorry, but would really appreciate instructions added to the readme for how to compile a DLL on OSX (the source comprises of a lot of files, and my compile time in Unity is becoming sluggish).  The latest Xamarin/Mono does not support .NET 3.5, and in MonoDevelop that ships with Unity, the .sln shows an error next to the UnityEngine reference, "Assembly not found for framework Mono / .NET 4.0".  Googling that suggests changing the target by going to the project Options > Build > General and changing the target there, but the General tab view is blank (the rest show data).  If I try to build anyway, I get the error "Error: Configuration '' not found in project 'FullSerializer - Unity' (FullSerializer - Unity)"

Sorry but this is literally the first DLL I am trying to build, I am not from Windows background...
Thanks.

**Comment by jacobdufault** [comment]
There are comments inside of the `Build Files (DLL)/CommonData.csproj` that explain what to do. I'll look into making the process easier.

**Comment by jpw** [comment]
OK thank you very much, if I can be of assistance please let me know.

**Comment by jacobdufault** [comment]
Fixed in aa68c85fc79d524335a84a898118d26864be7823.

All you need to do is run `$ ./BuildFiles/compile.sh`. If you have Unity installed somewhere other than `/Applications/Unity`, you'll need to specify it like this:

```
$ unity_path=/Applications/MyUnity ./BuildFiles/compile.sh
```

**Comment by jpw** [comment]
Works lovely, thank you so much for your efforts!
