### ISSUE TITLE
Unity 5.4 - compile.sh

### ISSUE THREAD

**Issue by giagkiozis** [jacobdufault/fullserializer#109]
In Unity 5.4 under OS X, due to some folder changes, compile.sh needs the following changes: 
line 22
* mcs_path=${mcs_path:-"$unity_path/Frameworks/MonoBleedingEdge/bin/mcs"}
to 
* mcs_path=${mcs_path:-"$unity_path/MonoBleedingEdge/bin/mcs"}

and (line 40)
* /lib:$unity_path/Frameworks/Managed \
to
* /lib:$unity_path/Managed \

Otherwise works like a charm.

**Comment by jacobdufault** [comment]
Thanks, I've changed how the automation is setup and upload the DLLs needed directly to the repro instead so this type of problem will not happen in the future.
