### ISSUE TITLE
Separate [NonSerialized] and [fsIgnore]

### ISSUE THREAD

**Issue by pointcache** [jacobdufault/fullserializer#111]
It's quite obvious: if you have a cyclic loop in unity and for it to stop throwing depth limit error you add
NonSerialized, you end up not serializing the thing you need to be serialized by Fs.
So yeah they must be separated.

**Comment by jacobdufault** [comment]
You can set this up by modifying your Full Serializer configuration (see [fsConfig](https://github.com/jacobdufault/fullserializer/blob/master/Assets/FullSerializer/Source/fsConfig.cs)).
