### ISSUE TITLE
You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  

### ISSUE THREAD

**Issue by heckubiss** [jacobdufault/fullserializer#112]
I get this warning.  how to resolve?
here are the details

this is what is in my readtofile()
`    public void ReadToFile()
    {
        Strdata = File.ReadAllText(Application.persistentDataPath + "/save.sav");
        data = fsJsonParser.Parse(Strdata);
        fsSerializer _serializer = new fsSerializer();
        _serializer.TryDeserialize(data, ref instance.savedGames).AssertSuccessWithoutWarnings(); //FSdata data, Type, object result
    }`
You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent().  Alternatively, your script can inherit from ScriptableObject or no base class at all
UnityEngine.MonoBehaviour:.ctor()
GameControl:.ctor()
System.Activator:CreateInstance(Type, Boolean)
FullSerializer.fsMetaType:CreateInstance() (at Assets/Scripts/Source/Reflection/fsMetaType.cs:301)
FullSerializer.Internal.fsReflectedConverter:CreateInstance(fsData, Type) (at Assets/Scripts/Source/Converters/fsReflectedConverter.cs:83)
FullSerializer.fsSerializer:InternalDeserialize_3_Inheritance(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:703)
FullSerializer.fsSerializer:InternalDeserialize_2_Version(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:652)
FullSerializer.fsSerializer:InternalDeserialize_1_CycleReference(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:616)
FullSerializer.fsSerializer:TryDeserialize(fsData, Type, Object&) (at Assets/Scripts/Source/fsSerializer.cs:587)
FullSerializer.Internal.fsReflectedConverter:TryDeserialize(fsData, Object&, Type) (at Assets/Scripts/Source/Converters/fsReflectedConverter.cs:70)
FullSerializer.fsSerializer:InternalDeserialize_5_Converter(fsData, Type, Object&) (at Assets/Scripts/Source/fsSerializer.cs:745)
FullSerializer.fsSerializer:InternalDeserialize_4_Cycles(fsData, Type, Object&) (at Assets/Scripts/Source/fsSerializer.cs:737)
FullSerializer.fsSerializer:InternalDeserialize_3_Inheritance(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:716)
FullSerializer.fsSerializer:InternalDeserialize_2_Version(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:652)
FullSerializer.fsSerializer:InternalDeserialize_1_CycleReference(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:616)
FullSerializer.fsSerializer:TryDeserialize(fsData, Type, Object&) (at Assets/Scripts/Source/fsSerializer.cs:587)
FullSerializer.Internal.fsIEnumerableConverter:TryDeserialize(fsData, Object&, Type) (at Assets/Scripts/Source/Converters/fsIEnumerableConverter.cs:67)
FullSerializer.fsSerializer:InternalDeserialize_5_Converter(fsData, Type, Object&) (at Assets/Scripts/Source/fsSerializer.cs:745)
FullSerializer.fsSerializer:InternalDeserialize_4_Cycles(fsData, Type, Object&) (at Assets/Scripts/Source/fsSerializer.cs:737)
FullSerializer.fsSerializer:InternalDeserialize_3_Inheritance(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:716)
FullSerializer.fsSerializer:InternalDeserialize_2_Version(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:652)
FullSerializer.fsSerializer:InternalDeserialize_1_CycleReference(fsData, Type, Object&, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:616)
FullSerializer.fsSerializer:TryDeserialize(fsData, Type, Object&) (at Assets/Scripts/Source/fsSerializer.cs:587)
FullSerializer.fsSerializer:TryDeserialize(fsData, List`1&) (at Assets/Scripts/Source/fsSerializer.cs:433)
NewSave:ReadToFile() (at Assets/Scripts/UI/NewSave.cs:96)
NewSave:Load2() (at Assets/Scripts/UI/NewSave.cs:206)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by jacobdufault** [comment]
Properly serializing MonoBehaviour's is tricky. See how Full Inspector does it [here](https://github.com/jacobdufault/fullinspector/blob/master/Assets/FullInspector2/Core/fiISerializedObjectUtility.cs#L42).

You can't directly allocate an instance - you need to get it by calling `AddComponent`, ie,

```c#
GameObject go = /* ... */;
var component = go.AddComponent<MyComponent>();
```
