### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by pjohalloran** [jacobdufault/fullserializer#113]
Hi,

Just wondering if FullSerializer is thread safe?

Im trying to do serialization/deserialization on threads on a project on Android and iOS but its not working for me on Android, whereas when i disable threading, it works perfectly.

There seems to be a few static dictionarys in places which means, even if i create 2 instances of the parser, it would not be thread safe, i guess?

Thanks.

**Comment by jacobdufault** [comment]
Thanks, I've added some locking.

FS should be fully thread safe on a per-serializer level. So each thread needs to have it's own fsSerializer instance.
