### ISSUE TITLE
How do I force serialization of static vars? 

### ISSUE THREAD

**Issue by masteranza** [jacobdufault/fullserializer#116]
I do not intend to deserialize (although it could be nice to have this just in case)

**Comment by jacobdufault** [comment]
I don't believe there is a way right now, without writing a custom converter.

Why do you want to only serialize statics?

You could work around the issue by doing something like

```
class Foo {
    static int a;
    [fsProperty]
    public int serializedA {
      get { return a; }
      set { a = value; }
    }
}

**Comment by masteranza** [comment]
thanks, I just intend to use it sometimes as a snapshot of certain variables from my classes.

**Comment by jacobdufault** [comment]
Sounds good - I'm going to close this issue then.
