### ISSUE TITLE
Invert [fsIgnore] effect

### ISSUE THREAD

**Issue by pointcache** [jacobdufault/fullserializer#123]
Hello im looking for a way to invert the way fs works, in that sense that i wan't to serialize fields selectively, like [fsSerialize] couple of em, while ignoring everything else, how would i go about that in a simple manner?
Currently what i can come up with is too stupid to be conveniently used.

**Comment by pointcache** [comment]
http://i.imgur.com/MqPezts.png

**Comment by pointcache** [comment]
Alright nevermind i found alternative solution.

**Comment by FunkMonkey** [comment]
@pointcache What was the solution that you ended up using? Thanks!

**Comment by pointcache** [comment]
wish i remembered...

**Comment by pointcache** [comment]
give me some time maybe it'll come up
