### ISSUE TITLE
Serialize String as Key Dictionaries Cleanly

### ISSUE THREAD

**Issue by izackp** [jacobdufault/fullserializer#16]
By default fullserializer will not deserialize something like this json:
```
{
  "controls": {
    "Action1": "Roll",
    "Action2": "Throw Knife",
    "Action3": "Smoke Bomb",
    "Action4": "4"
  }
}
```
into a dictionary for a class like this:
```
public class CharacterDesc {
	[fsProperty("controls")]
	public Dictionary<string, string> Controls;
}
```
I implemented myself, but I'm too lazy to rearrange my code and make a pull request:
https://gist.github.com/izackp/39e1e150b41fced0680a

**Comment by jacobdufault** [comment]
Okay, I'll take a look into integrating this. If I do so, I'd probably just integrate it directly into the `IEnumerable` converter instead of making users deal with a special dictionary class.

**Comment by izackp** [comment]
Ya, I'm a pretty new c# developer :S so I didn't know the best way to accomplish it.

**Comment by jagt** [comment]
+1 for this. It would really handy to work with hand written JSON files with this integrated.

**Comment by jacobdufault** [comment]
Yep, I plan on integrating this when I get some time to work on it
