### ISSUE TITLE
The type or namespace name 'ExpectedException' could not be found

### ISSUE THREAD

**Issue by Niehaus** [jacobdufault/fullserializer#166]
By using NUnit 3.0, this error occours because the ExpectedExceptionAttribute has been removed. So instead it should be using a construct like the Throws Constraint.

Use this `Assert.Throws<Exception>(()=>MethodThatThrows());` instead of this ` [ExpectedException(typeof(Exception))]` to test for exception 

We can see more about NUnit exceptionAsserts in here: https://docs.nunit.org/2.5/exceptionAsserts.html

**Comment by zenith4eva** [comment]
This is still happening

**Comment by OeilDeLance** [comment]
I Confirm that, to repro just use Unity 2021.3 or up I think, I fixed it like that 
 [Test]
 public void DuplicateVersionString() {
		Assert.That(() => fsVersionManager.GetVersionedType(typeof(VersionedModelDuplicateVersionString)),
			Throws.TypeOf<fsDuplicateVersionNameException>());
 }

 [Test]
 public void MissingConstructor() {
		Assert.That(() => fsVersionManager.GetVersionedType(typeof(VersionedModelMissingConstructor)),
			Throws.TypeOf<fsMissingVersionConstructorException>());
		;
 }
