### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by Doolwind** [jacobdufault/fullserializer#17]
I've tried using FullSerializer (via source installation) with the Unity 5 release candidate (f1) WebGL exporter. When I try and serialize an object using StringSerializationAPI I get the following error:

TypeLoadExeption: A type load exception has occurred.

Looking at the stack trace, the specific line in the .NET framework is System.Type.MakeGenericType(System.Type[] typeArguments) and the lowest line in FullSerializer is FullSerializer.Internal.fsMetaProperty.Read(System.Object context)

Am I doing something wrong or is the WebGL exporter not yet supported?

**Comment by jacobdufault** [comment]
That's interesting - there should be no calls to MakeGenericTypes in Full Serializer as it breaks on AOT platforms. Can you post the code you are serializing that breaks WebGL?

**Comment by Doolwind** [comment]
I just tried with a simpler class and it still threw the same exception. The simple class looks like:

public class TokenResponse
{
    public string access_token { get; set; }
    public string token_type { get; set; }
    public int expires_in { get; set; }
}

**Comment by jacobdufault** [comment]
I'm unable to reproduce this issue. Can you verify it still occurs on rc2 and send me a full project with the error occurring?

**Comment by Doolwind** [comment]
Just tried again in rc2 and I'm getting the exception still. I've put together an example project, let me know where I can email a link to.

**Comment by jacobdufault** [comment]
Feel free to send it to {myname}@gmail.com

**Comment by jacobdufault** [comment]
This looks like a bug in il2cpp. I'll submit a bug report. For the time being however, you can use

```c#
// no auto-properties
public class TokenResponse
{
    public string access_token;
    public string token_type;
    public int expires_in;
}
```

which works as expected in WebGL.

**Comment by Doolwind** [comment]
Thanks!
