### ISSUE TITLE
Corrupted JSON on some locales. Double.ToString() returns ',' delimeter

### ISSUE THREAD

**Issue by dippnsk** [jacobdufault/fullserializer#21]
When use Unity '-batchmode' from Termnal on Mac OS X with RU locale, Double.ToString() returns comma delimeter instead of dot.
As a result, we get JSON like this:
```
{ "value":0,5.5 }
```

Possible fix is to add InvariantCulture to ToString calls in fsJsonPrinter:
```
if (Double.IsInfinity(d) || Double.IsNaN(d)) return d.ToString(System.Globalization.CultureInfo.InvariantCulture);
String doubledString = d.ToString(System.Globalization.CultureInfo.InvariantCulture);
```

**Comment by jacobdufault** [comment]
Ha, wow. Thanks

**Comment by dippnsk** [comment]
I think in TryParseNumber method you must also make the same fix:
```
double.TryParse(numberString, NumberStyles.Any, CultureInfo.InvariantCulture, out doubleValue);
```
According to this: http://stackoverflow.com/a/19678636/940038.

**Comment by jacobdufault** [comment]
Thanks, I've added changes for parsing as well. Let me know if you find any other issues - setting this type of environment up for testing is pretty painful.
