### ISSUE TITLE
Support for Observableproperties

### ISSUE THREAD

**Issue by NVentimiglia** [jacobdufault/fullserializer#23]
I am officially using FullSerializer for the Foundation Databinding toolkit

https://github.com/NVentimiglia/Unity3d-Databinding-Mvvm-Mvc

I noticed that observable properties are not automatically serialized. I had to use the [fsProperty] annotation to get them to work. Support for the following (without the fsProperty) would be awesome.

`````c#
 private int _networkId =-1;
        /// <summary>
        /// Network Connection Id
        /// </summary>
        [fsProperty("NetworkId")]
        public int NetworkId
        {
            get { return _networkId; }
            set
            {
                if (_networkId == value)
                    return;
                _networkId = value;
                NotifyProperty("NetworkId", value);
            }
        }
`````

**Comment by jacobdufault** [comment]
Only auto-properties are serialized by default (this is intentional). You may be interested in the [fsObject] annotation, particularly [this](https://github.com/jacobdufault/fullserializer/blob/master/Source/fsObjectAttribute.cs#L31) field.

**Comment by jacobdufault** [comment]
See [here](https://github.com/jacobdufault/fullserializer/blob/master/Source/fsMemberSerialization.cs) for `fsMemberSerialization`
