### ISSUE TITLE
Remove $type field

### ISSUE THREAD

**Issue by NVentimiglia** [jacobdufault/fullserializer#27]
I noticed that the serializer adds a $type field to serialized objects. What would the quickest way to remove the $type field ? Is this something I can handle in my interface class ?

**Comment by jacobdufault** [comment]
The `$type` field is emitted during serialization when there will not be enough context to fully recover the object graph during serialization (specifically, the type of object that the JSON maps back to).

If you remove `$type`, then deserialization will not work.

I'll look into adding a config to allow FS to act more like a JSON dumper, which sounds to be more like what you want (noticing some of the other issues you created).

**Comment by NVentimiglia** [comment]
Gotcha. Is this an issue if I pass a specific type along with the json (Am I to understand that FS actually can detect my object? TIL, cool) ?

See my API wrapper :
https://github.com/NVentimiglia/Unity3d-Databinding-Mvvm-Mvc/blob/master/Foundation%20Databinding/Assets/Plugins/JsonSerializer.cs 

Im my scenario I am deserializing server side and it just so happens that. I receive exceptions if my json contains illegal properties. The ability to remove properties post-deserialization is good enough for me.

**Comment by jacobdufault** [comment]
I looked into adding a mode to prevent deserialization metadata from being added (like `$type`), but it mucks around with the logic a bit too much (and completely breaks serialization in certain scenarios, ie, when there is a cyclic object graph).

I've included a post-processor that removes the annotations in `fsSerializer`. Here is an example of how to use it:

```c#
void DoSerialize<T>(T obj) {
    fsData data;
    Serializer.Serialize(obj, out data).AssertSuccessWithoutWarnings();
    fsSerializer.StripDeserializationMetadata(ref data);
}
```

**Comment by NVentimiglia** [comment]
I can work with that.
