### ISSUE TITLE
Better Converter Example

### ISSUE THREAD

**Issue by NVentimiglia** [jacobdufault/fullserializer#28]
I do not understand how to use the json converters. Other converters are easy to understand. Take LITJson for instance. In LIT you manually you have access to a writer object with methods for writing each part of the object as json. Newtonsoft has a similar feature.

`````
  public static void FilterExporter(MyObject value, JsonWriter writer)
        {
            writer.WriteObjectStart();

            writer.WritePropertyName("operator");
            writer.Write(value.op.ToString());

            if (!string.IsNullOrEmpty(value.item))
            {
                writer.WritePropertyName("item");
                writer.Write(value.item);
            }

            writer.WritePropertyName("value");
            WriteValue(value.value, writer);

            writer.WriteObjectEnd();
        }
`````

Looking at the examples I was unable to discern how I could go about writing a custom filter for an arbitrary object.

**Comment by jacobdufault** [comment]
I've updated the readme with better/more examples. Would you mind taking a look through it? Let me know if you need more info and I'll try to add more.
