### ISSUE TITLE
Serialize float without convertion to double

### ISSUE THREAD

**Issue by dippnsk** [jacobdufault/fullserializer#33]
When serializing float values, fsPrimitiveConverter converts it to double. This adds some very small floating point jitter which leads to saving values using much more space in Json:
0.800000011920929
0.600000023841858
0.300000011920929
instead of normal 0.8, 0.6, etc.

When deserializing this value to float, all this noise won't fit to float and it's actually useless.

You can try it out yorself and see different result with simple code:
```
Debug.Log(0.1f); // prints 0.1
Debug.Log((double)0.1f); // prints 0.100000001490116
Debug.Log(0.1); // prints 0.1
```

If serializable type is float, convertion to double must not be preformed.

**Comment by jacobdufault** [comment]
Okay, I'll try to get this fixed - but it may be a little while before I can get to it. The only solution I can think of right now is a bit hacky.

**Comment by jacobdufault** [comment]
I should comment that the hacky solution is to store the float inside of the `fsData` boxed referenced, (and transparently change it to a double as needed - probably use the same logic for long values as well). The JSON printer will be aware that it was a float and would not cast it to a double when emitting JSON.

**Comment by dippnsk** [comment]
Thanks. This is not urgent at all, but definetly need to be fixed.
