### ISSUE TITLE
ability to convert json keys to different format without manual addition of fsProperty attribute on all properties

### ISSUE THREAD

**Issue by r0bbyboy** [jacobdufault/fullserializer#34]
On our project we like have our json look like this:

{ "propertyKey" : "value" }

but the corresponding property in our code would be:

public string PropertyKey { get; set; }

or a more complicated example would be "property_key" => "PropertyKey"

It would be nice to be able to have a global rule for parsing that handles this rather than tons of fsProperty attributes. Newtonsoft's json.net handles this using something they call Contract Resolvers:
http://www.newtonsoft.com/json/help/html/ContractResolver.htm

I can't find an equivalent in FullSerializer. Am I missing something?

**Comment by jacobdufault** [comment]
There is currently no equivalent. I'll look into adding something like this.
