### ISSUE TITLE
better Unity AOT example

### ISSUE THREAD

**Issue by r0bbyboy** [jacobdufault/fullserializer#37]
The section in the readme regarding compiling AOT converters for unity builds is unclear. I attempted making a menu option to generate my converters using the provided method (which is slightly out of date) inside an editor script. That method on its own does nothing without types being added to the AvailableAotCompilations list but the readme provides no information on how best to populate that list. Any advice would be appreciated.

**Comment by jacobdufault** [comment]
Okay, I'll write some more docs on it. The list is automatically populated as the serializer encounters things. You can request an AOT compilation via [this](https://github.com/jacobdufault/fullserializer/blob/master/Source/fsAotCompilationManager.cs#L44) method.

**Comment by r0bbyboy** [comment]
I've got a method working that builds these AOT converters but I'm not sure how I should add them to my serializer. Is there a way of adding all the converters from the ConverterRegistar to my serializer without using reflection?

**Comment by jacobdufault** [comment]
You can call `serializer.AddConverter(...)` manually for each generated converter where serializer is your `fsSerializer` instance.

**Comment by r0bbyboy** [comment]
Ah I see. Btw, here is a method I've written that will walk and Assembly and generate a converter for all classes that contain at least one fsProperty.

```
static void GenerateAotConverters(Assembly assembly)
{
	string directory = Path.Combine("Assets", "AOT");
	if(!System.IO.Directory.Exists(directory))
	{
		System.IO.Directory.CreateDirectory(directory);
	}

	foreach(Type t in assembly.GetTypes())
	{
		foreach(PropertyInfo p in t.GetProperties())
		{
			object[] props = p.GetCustomAttributes(typeof(fsPropertyAttribute), true);
			if(props.Length > 0)
			{
				string compilation = null;
				if(fsAotCompilationManager.TryToPerformAotCompilation(t, out compilation))
				{
					string filename = string.Format("AotConverter_{0}.cs", t.CSharpName(true, true));
					string path = Path.Combine(directory, filename);
					System.IO.File.WriteAllText(path, compilation);
					break;
				}
			}
		}
	}
}
```

**Comment by jacobdufault** [comment]
Thanks, I've updated the docs in that section. Hopefully they are clearer. I've also incorporated some of the code sample above (thanks!).
