### ISSUE TITLE
Errors on compile in Unity 4.6.3

### ISSUE THREAD

**Issue by DavidENishball** [jacobdufault/fullserializer#38]
I am attempting to use fullserializer for my unity 4.6.3 project.  However, I get the following errors when attempting to build.
http://puu.sh/hpHKW/b277078a90.png

fsEnumConverter.cs(39,52) Type 'StringBuilder' does not contain a definition for 'Append'
fsEnumConverter.cs(41,32) Type 'StringBuilder' does not contain a definition for 'Append'
fsJsonParser.cs(251,85): Type 'StringBuilder' does not contain a constructor that takes '1' argument.

This appears to be due to Unity using an older equivalent version of .Net, one without the extra methods and constructors for StringBuilder class.  I am wondering how you managed to work around this problem?

**Comment by jacobdufault** [comment]
Wow, how strange. Can you please verify that there is not another class in your project called `StringBuilder`? What .NET profile setting are you on?

**Comment by DavidENishball** [comment]
Ah, you are right.  There was a custom StringBuilder class from an early version of the project.  Renaming it fixed the errors.  Thank you!
