### ISSUE TITLE
Unable to parse 2015-04-27T15:54:02.763033Z into a DateTime

### ISSUE THREAD

**Issue by boudinov** [jacobdufault/fullserializer#40]
Hello,
I am using FullSerializer in Unity, and for certian DateTimes, I get fsResult from TryDeserialize with HasWarnings = true, and a formatted message like the one above.
Note that there are no such problems for DateTimes with 7 deciseconds symbols behind the last Dot.

For example, 2015-04-27T15:54:02.7630331Z works fine.

The result come from the default Json.NET serializer with Microsoft Web Api.
Any idea if this is a bug?

And btw, fsResult.HasErrors method should first check if _message != null?

Thanks

**Comment by jacobdufault** [comment]
Thanks, I've fixed the `HasWarnings` issue. I'll push it up shortly.

I'm not terribly familiar with `DateTime` formatting/parsing. The current does does it as follows:

```c#
DateTime result;
if (DateTime.TryParse(data.AsString, null, DateTimeStyles.RoundtripKind, out result)) {
    instance = result;
    return fsResult.Success;
}

return fsResult.Fail("Unable to parse " + data.AsString + " into a DateTime");
```

Any ideas?

**Comment by boudinov** [comment]
Yeah, it seems it is a bug for Unity's Mono only. It parses only datetimes with 7 milisecond symbols.

**Comment by jacobdufault** [comment]
Closing since there isn't much I can do on my end besides reimplementing `DateTime`.
