### ISSUE TITLE
Crash on WP8 in fsMetaType.Create().

### ISSUE THREAD

**Issue by pjohalloran** [jacobdufault/fullserializer#41]
Hi!
I am using NodeCanvas v2, a project that uses fullserializer as you are probably aware. I am experiencing a crash on WP8 in fsMetaType, beginning line 292.
`try {
    return Activator.CreateInstance(ReflectedType, /*nonPublic:*/ true);
}`

Same crash was reported elsewhere on WP8 in an unrelated project with a google search http://opsive.com/forum/index.php/topic,635.15.html

If you use instead the type Constructor (https://msdn.microsoft.com/en-us/library/wccyzw83%28v=vs.110%29.aspx) then it doesn't crash.

I am not sure what effect this has on platforms other than WP8.

If you would like I can fork, open a PR and make the change.

Thanks,
PJ

**Comment by pjohalloran** [comment]
Sorry, to be more specific about the crash...

When that line is executed, it generates a System.ExecutionEngineException and terminates the app on WP8.

**Comment by jacobdufault** [comment]
Thanks! I've implemented the fix.
