### ISSUE TITLE
fsObjectProcessor - OnBeforeDeserialize and "$type"

### ISSUE THREAD

**Issue by nuverian** [jacobdufault/fullserializer#42]
Hello Jacob,

After updating to the latest FS, I am encountering an issue with OnBeforeDeserialize of the fsObjectProcessor and a trick I used that modifies the "$type" json entry of the object proccessed.
As it seems the json deserialized is not being modified at all now. This used to work great a couble of versions back (about 3 weeks ago).
Here is the critical part of the processor code:

		public override void OnBeforeDeserialize(Type storageType, ref fsData data){

			if (data.IsNull)
				return;

			var json = data.AsDictionary;

			if (json.ContainsKey("$type")){

				var serializedType = ReflectionTools.GetType( json["$type"].AsString );
				if (serializedType == null){
					json["$type"] = new fsData( typeof(MissingNode).FullName );
				}
			}
		}

Thanks a lot!
Gavalakis Vaggelis

**Comment by jacobdufault** [comment]
I'll take a look this weekend, but this is almost certainly related to 414e21ee0b4ccf33af773a93fdad8bd9a84c9cf0.

**Comment by jacobdufault** [comment]
What does the `CanProcess` function look like?

If it looks like `typeof(BaseNode) == type`, can you try changing it to `return typeof(BaseNode).IsAssignableFrom(type)` instead?

I made a change so that processors are resolved based on the actual instance type instead of the type passed in - still thinking about the proper behavior. I may revert it to be based on the declared deserialization type and not the instance type.

**Comment by jacobdufault** [comment]
Also, is `OnBeforeDeserialize` actually getting invoked?

**Comment by nuverian** [comment]
Hey Jacob,

Thanks for taking a look into it.
Sorry. I forgot to mention it initialy, but `OnBeforeDeserialize` is called normaly yes. That's the most weird part actually.

CanProcess is also "declared" like `typeof(BaseNode).IsAssignableFrom(type)`.

Right after `OnBeforeDeserialize` is called, the error "Cannot create an instance of an interface or abstract type for BaseNode" is thrown, which is normaly the case when the serialized $type is missing. That's what I am trying to handle in `OnBeforeDeserialize` by altering the serialized information.

This used to work a couple of version back. I can't really say why it doesn't now :)
If you need more information, please let me know.

Thanks a lot!

**Comment by jacobdufault** [comment]
I believe the given commit should fix the issue. Let me know.

**Comment by nuverian** [comment]
Hey Jacob,

Everything works fine again with the latest commit.

Thanks a lot!
