### ISSUE TITLE
Compile errors on WSA.

### ISSUE THREAD

**Issue by pjohalloran** [jacobdufault/fullserializer#43]
Hi,
Im using FullSerializer in NodeCanvas and i'm getting compile errors in fsTypeExtensions.cs. They can probably be fixed easily enough with a NETFX_CORE defines.

Here are the errors. Thanks!
PJ

Assets\NodeCanvas\Framework\_ParadoxNotion (shared)\Runtime\Serialization\FullSerializer\Internal\fsTypeExtensions.cs(41,60): error CS1061: 'System.Type' does not contain a definition for 'GetGenericArguments' and no extension method 'GetGenericArguments' accepting a first argument of type 'System.Type' could be found (are you missing a using directive or an assembly reference?)
Assets\NodeCanvas\Framework\_ParadoxNotion (shared)\Runtime\Serialization\FullSerializer\Internal\fsTypeExtensions.cs(51,40): error CS1061: 'System.Type' does not contain a definition for 'GetGenericArguments' and no extension method 'GetGenericArguments' accepting a first argument of type 'System.Type' could be found (are you missing a using directive or an assembly reference?)
Assets\NodeCanvas\Framework\_ParadoxNotion (shared)\Runtime\Serialization\FullSerializer\Internal\fsTypeExtensions.cs(52,81): error CS1061: 'System.Type' does not contain a definition for 'GetGenericArguments' and no extension method 'GetGenericArguments' accepting a first argument of type 'System.Type' could be found (are you missing a using directive or an assembly reference?)

**Comment by pjohalloran** [comment]
Adding this code fixes compile errors:

Firstly:
```
#if NETFX_CORE
using System.Reflection;
#endif
```

Then later:
```
#if NETFX_CORE
var genericArguments = (IEnumerable<Type>)type.GetTypeInfo().GenericTypeArguments;
#else
var genericArguments = (IEnumerable<Type>)type.GetGenericArguments();
#endif
            if (type.IsNested) {
                name += type.DeclaringType.CSharpName() + ".";

                // The declaring type generic parameters are considered part of the nested types generic
                // parameters so we need to remove them, otherwise it will get included again.
                //
                // Say we have type `class Parent<T> { class Child {} }`
                // If we did not do the removal, then we would output Parent<T>.Child<T>, but we really want
                // to output Parent<T>.Child
#if NETFX_CORE
if (type.GetTypeInfo().DeclaringType.GetTypeInfo().GenericTypeArguments.Length > 0) {
genericArguments = genericArguments.Skip(type.GetTypeInfo().DeclaringType.GetTypeInfo().GenericTypeArguments.Length);
}
#else
if (type.DeclaringType.GetGenericArguments().Length > 0) {
genericArguments = genericArguments.Skip(type.DeclaringType.GetGenericArguments().Length);
}
#endif
            }
```

**Comment by jacobdufault** [comment]
Thanks, I have pushed a fix. I have some compatibility shims in place, but they reside in `FullSerializer.Internal`, so the only fix required is to add an import.
