### ISSUE TITLE
BSON support

### ISSUE THREAD

**Issue by heckubiss** [jacobdufault/fullserializer#44]
I have a  list of abstract data class i would like to serialize to a file.
public List<SomeClass> level = new List<SomeClass> ();

I tried doing it with the Unity serializer. I am able to write and read from a file but when i read back, the data is incorrect so I thought I would try full serializer

I was able to get to this point but not sure how to send to a file and then deserialize

// add stuff to level

		object classdata= level;
		fsData data;
		fsSerializer _serializer = new fsSerializer();
		_serializer.TrySerialize(classdata, out data).AssertSuccessWithoutWarnings();

**Comment by jacobdufault** [comment]
Do `System.IO.File.ReadAllText` and `System.IO.File.WriteAllText` work?

Ie,

Saving the JSON to disk:
`System.IO.File.WriteAllText("state", fsJsonPrinter.PrettyJson(data))`

Restoring the JSON from disk:
`fsData data = fsJsonParser.Parse(System.IO.File.ReadAllText("state"))`

Please also see the `StringSerializationAPI` in the README.

See:
- https://msdn.microsoft.com/en-us/library/system.io.file.readalltext(v=vs.110).aspx
- https://msdn.microsoft.com/en-us/library/system.io.file.writealltext(v=vs.110).aspx

**Comment by heckubiss** [comment]
OH sorry , I think I asked the wrong question.
How can I take a class and Serialize to binary?

**Comment by jacobdufault** [comment]
What do you mean by binary? [BSON](http://bsonspec.org/) is not currently supported - I'd be happy to accept a pull request though if you implemented it via a `fsBsonPrinter` similar to `fsJsonPrinter`.

**Comment by jacobdufault** [comment]
Closing for now. Feel free to submit a PR with BSON support and I'll integrate it into the main repro.
