### ISSUE TITLE
Deserialization not invoking processors when actual type != storage type

### ISSUE THREAD

**Issue by DenL** [jacobdufault/fullserializer#45]
Steps to reproduce:
1. Instantiate a ClassA object which implements IInterface, put it in an IInterface object
2. Serialize the IInterface object (which is actually ClassA), processors of ClassA gets called
3. Try to deserialize output from step 2 into an IInterface object, processors of ClassA does not get called
Verified that serialized data does contain type information, which is ClassA.

Thanks for reading!

**Comment by DenL** [comment]
Just saw the latest commit and looks like you are aware of the issue and are considering using object type to fetch processors. I would like to make an argument for the case.

A common use case is that multiple classes, derived from the same class or implementing same interface, can be serialized/deserialized using the same code without having to write custom handlers for each class (passing the base class/interface as container). In this case processors will be called while serializing but not while deserializing and this is inconsistent.

Thanks for reading.

**Comment by jacobdufault** [comment]
Yes, I think using the object type is the correct approach. I'll switch the code to use that in the future in the near future.

**Comment by drostar** [comment]
Has this been implemented yet? I'm having a similar issue.

**Comment by jacobdufault** [comment]
This fix may break NodeCanvas, though I don't think it will. Checking with @nuverian.
