### ISSUE TITLE
Classes need default constructor

### ISSUE THREAD

**Issue by Bulkman** [jacobdufault/fullserializer#46]
class need default constructor in order to run on Android. MissingMethodException: Method not found: 'Default constructor not found...ctor() of FullSerializer.Internal.DirectConverters.AnimationCurve_DirectConverter'.

suppose this is not the only one

**Comment by jacobdufault** [comment]
That's... unexpected. The class definitely has a default ctor. Is there more to the stack trace?

**Comment by jacobdufault** [comment]
Can you also try changing [this](https://github.com/jacobdufault/fullserializer/blob/master/Source/fsSerializer.cs#L290) line to be

```
AddConverter((fsBaseConverter)Activator.CreateInstance(converterType, true));
```

**Comment by MischaWeerwag** [comment]
Also having this problem. Changing that line doesnt help.
Disabling stripping does help though. Not sure what this can be.

**Comment by jacobdufault** [comment]
Thanks @MischaWeerwag, I've added a note to the README about this in 14d7c7c15b1332f4a49fdc8f76565c4d9cc775d4.
