### ISSUE TITLE
How to use AOT Converters

### ISSUE THREAD

**Issue by treefortress** [jacobdufault/fullserializer#50]
I'm not quite sure how to get this working on PS4 with in full-AOT mode.

I've marked all classes with [fsObject] and the aot-converter-classes are being generated successfuly, but I'm still getting errors when trying to serialize: 

Attempting to JIT compile method '(wrapper delegate-invoke) <Module>:invoke_AppSettings__this___SaveData (SaveData)' while running with --aot-only.
http://gyazo.com/fbc2428cfe9b2b9d51c5efad9fbe7d14

Is there any other steps I should be doing? Do I need to manually register the converters with the serializer?

**Comment by jacobdufault** [comment]
Can you copy+paste the aot converter file for `SaveData`? Registration should happen automatically with [fsConverterRegistrar](https://github.com/jacobdufault/fullserializer/blob/master/Source/fsConverterRegistrar.cs).  It looks like the aot converter is not getting used. Maybe put a `Debug.LogError` in `fsReflectedConverter.TrySerialize` with the type?

If you can send me the project at my email ([myname]@gmail.com) then I can take a closer look as well.

**Comment by treefortress** [comment]
Ok, I think I got to the bottom of it. The aotConverter for my SaveData class was failing, I didn't notice as the other 17 classes were created successfully.

Turns out the problem was read-only virtual-properties

You can reproduce with something like this:
[fsObject]
public class SerializeTest {
    public int Foo { get; private set; }
}

Workarounds are to just make the property public, or, manually back it with a variable:
public class SerializeTest {
    int foo;
    public int Foo { get { return foo; } private set { foo = value; } }
}

**Comment by jacobdufault** [comment]
Okay, good to know. Unfortunately it isn't technically possible to work around this on my end.

**Comment by treefortress** [comment]
Ok, no big deal, might be a good idea to call it our in the readme though, as this seems misleading:
"Auto-properties that are at least partially public are serialized by default"

Also, I've just realized that Internal properties are ignored by the serializer as well.

Makes sense that it's not technically possible to serialize these, but since the Unity serializer does work on both types, it can lead to some confusion.
