### ISSUE TITLE
using FullSerializer.Internal;

### ISSUE THREAD

**Issue by NVentimiglia** [jacobdufault/fullserializer#52]
fsTypeExtensions.cs needs to reference FullSerializer.Internal;

please add :

`````
     using FullSerializer.Internal;

`````

https://github.com/jacobdufault/fullserializer/blob/master/Source/Internal/fsTypeExtensions.cs

**Comment by jacobdufault** [comment]
Why?

**Comment by jacobdufault** [comment]
Thanks; fixed in b2bfe2adc7a155911c0f973eccd59016ff6f0813.
