### ISSUE TITLE
Parser throws an exception on empty input

### ISSUE THREAD

**Issue by dippnsk** [jacobdufault/fullserializer#58]
Hello,

I've recently tested some stuff and found that fsJsonParser throws an exception if empty string was passed to it. I think this is not best behaviour, and we must have fsResult.Fail for that case instead of exception.

**Comment by jacobdufault** [comment]
Okay, a proper error is now given. I've also fixed a scenario where the parser would crash on

```json
{
    "hello":
```

**Comment by dippnsk** [comment]
Cool, thanks!
