### ISSUE TITLE
fsConfig must not be shared between Full Inspector and any other fsSerializer

### ISSUE THREAD

**Issue by dippnsk** [jacobdufault/fullserializer#62]
Hi Jacob,

When I use Full Inspector and try to perform custom serialization from the editor scripts, I have a case where I need to modify Ignore/Serialize attributes. This is very fragile situation - I need to be sure to restore this attributes right away, or it will lead to some weird behavior, such as losing Full Inspector-serialized content. This is going from the fact, that fsConfig got shared between Full Inspector internal instance of serializer and any other instance of fsSerializer.

I think it will be much safer to have the ability to use a dedicated instance of fsConfig for any instance of fsSerializer (and use it inside Full Inspector).

**Comment by jacobdufault** [comment]
So if you send all of your serialization through a helper method, can you just enable/disable the properties in that helper method, thereby wrapping this complexity so that you don't need to worry about it?

**Comment by dippnsk** [comment]
I use a helper method and do setup/reset inside of it. But before that I got all of the problems described here. For any new user this again may be a pain.
