### ISSUE TITLE
fsLazyCycleDefinitionWriter not clears _references field

### ISSUE THREAD

**Issue by dippnsk** [jacobdufault/fullserializer#64]
FulInspector uses cached instance of serializer, and in this case, field _references not get cleared on every serialization process. I don't actually understand - is this desired behaviour or not.

Anyway, I have $id fields in places where they are not required (there is no corresponding $ref field).

**Comment by jacobdufault** [comment]
Can you post a code sample where this is happening? The references should be cleared after the top-level call to fsSerializer.TrySerialize returns.

**Comment by dippnsk** [comment]
The problem with the member in `fsLazyCycleDefinitionWriter`:
```csharp
private HashSet<int> _references = new HashSet<int>();
...
public void Clear() {
    _pendingDefinitions.Clear();
    _references.Clear(); // I had to add this line to remove unnecessary $id fields
}
```

There is no sample code, this fields just get saved to `*.asset` files when FullInspector does his job. Problem become visible when in one of the ScriptableObjects I've made a Duplicate instance in the list, so I began to see `<cycle>` on second item in list. After this, in any ScriptableObjects, that must be serialized/saved after this first, I've started to see this "$id":"0" values.

**Comment by jacobdufault** [comment]
Are you running Serialize on an array of ScriptableObjects, or are you calling serialize separately for each item in the array?

We want to maintain cyclic references between items in an array to preserve object graphs.

**Comment by mwgray** [comment]
Hi @jacobdufault,

I just went through the same process @dippnsk did to find the references were not being cleared.  Adding the line fixed the issue for me as well.  I simple have several BaseScriptableObjects and save in Unity, nothing out of the ordinary in terms of how serializing is happening.

What I observed:
* fsLazyCycleDefinitionWriter is part of fsSerializer, which is created only once, as a singleton
* fsLazyCycleDefinitionWriter._references is never cleared or has remove calls
* Therefore, the references always remain and cause false positive $id/$ref tags to linger in the data.

This happens across many of my BaseScriptableObjects.  During a save, if you observe the value of FullSerializerSerializer.Serializer._lazyReferenceWriter._references.Count, it never goes down, even across multiple BaseScriptableObject serializations.  It seems as if data from one BaseScriptableObject is creating a false positive on $id/$ref calculations during a separate BaseScriptableObject serialization.

I'm in a similar boat as @dippnsk, as I don't know the full context of the code, but the expectation I have is that each BaseScriptableObject would have it's own $id/$ref context and should be cleared each time serialization is complete for a give object.

**Comment by jacobdufault** [comment]
@mwgray, I'll take a look soon. Is there a test case that repros this concisely?

**Comment by mwgray** [comment]
All I had were two ScriptableObjects with Lists in them.  You can observe
that the references never get cleared across both objects.

**Comment by jacobdufault** [comment]
I'm having trouble reproducing, though the rationale by @mwgray makes sense. I've submitted a commit with the fix from @dippnsk.
