### ISSUE TITLE
WinRT build & fsPortableReflection.cs

### ISSUE THREAD

**Issue by tswalker** [jacobdufault/fullserializer#68]
was curious if the WinRT build is required for UWP builds?

as I was to build DLL for WinRT, shows:

Severity	Code	Description	Project	File	Line
Error	CS1503	Argument 1: cannot convert from 'System.Reflection.TypeInfo' to 'System.Type'	FullSerializer - Unity - WinRT	F:\Development\Full Serializer\Source\Internal\fsPortableReflection.cs	54

resulting also in:
Severity	Code	Description	Project	File	Line
Error	CS1061	'Type' does not contain a definition for 'IsGenericType' and no extension method 'IsGenericType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	FullSerializer - Unity - WinRT	F:\Development\Full Serializer\Source\Converters\fsIEnumerableConverter.cs	50

what am I missing here?

I had to add the following for the Unity version build to fsISerializationCallbacks:

#if !NO_UNITY
using UnityEngine;
#endif
...
and wrap:
#if !NO_UNITY
    
    public class fsSerializationCallbackReceiverProcessor : fsObjectProcessor {
        public override bool CanProcess(Type type) {
            return typeof(ISerializationCallbackReceiver).IsAssignableFrom(type);
        }

        public override void OnBeforeSerialize(Type storageType, object instance) {
            ((ISerializationCallbackReceiver)instance).OnBeforeSerialize();
        }

        public override void OnAfterDeserialize(Type storageType, object instance) {
            ((ISerializationCallbackReceiver)instance).OnAfterDeserialize();
        }
    }
#endif

**Comment by jacobdufault** [comment]
Sorry, this accidentally got broken. It looks like #67 fixes this though.
