### ISSUE TITLE
TrySerialize result doesn't chain warnings?

### ISSUE THREAD

**Issue by cfoulston** [jacobdufault/fullserializer#70]
Hi, I'm trying to retrieve the warnings from my custom fsDirectConverter but after everything has been serialized the final result doesn't contain any of my warning messages.

Chaining errors in TryDeserialize does work. Looks like you're using (ref result) during Deserialize, but not during Serialize

How can I find all errors/warnings that occured during a TrySerialize?

**Comment by jacobdufault** [comment]
Can you post some sample code? All of the warnings should be present in the `fsResult` instance returned from `TrySerialize`.

**Comment by jacobdufault** [comment]
I'm having some trouble reproducing this. I added a test that verifies warnings are propagated from `fsDirectConverters` in 6c2ea3969d57935433adcb93ab68c674e1ea0848.

If you're still able to reproduce this, please reopen this issue with some repro code. Thanks!
