### ISSUE TITLE
Nullable types are not supported

### ISSUE THREAD

**Issue by jfperusse-bhvr** [jacobdufault/fullserializer#71]
Hi, it seems like nullable types (e.g. "DateTime?", that is "typeof(DateTime?)") are not supported by fsSerializer. When deserializing these types, the variables remain null.

Do you plan on adding support for nullable types?

**Comment by jacobdufault** [comment]
This should be working (there's a test for `DateTime?` specifically).

If this is still an issue, can you reopen with a repro case? Thanks!
