### ISSUE TITLE
ISerializationCallbackReceiver not found in Interface fsISerializationCallbacks

### ISSUE THREAD

**Issue by Tulrath** [jacobdufault/fullserializer#72]
Using Unity 5.2.2, copied "Source" directory to project's Asset folder, receiving these errors:

Severity	Code	Description	Project	File	Line
Error	CS0246	The type or namespace name 'ISerializationCallbackReceiver' could not be found (are you missing a using directive or an assembly reference?)	bitterplants.CSharp	C:\Users\Darrel Cusey\Documents\Unity Projects\bitterplants\Assets\Source\fsISerializationCallbacks.cs	67

This is solved by changing lines 67, 71, and 75 to include "UnityEngine.":

#if !NO_UNITY
    public class fsSerializationCallbackReceiverProcessor : fsObjectProcessor {
        public override bool CanProcess(Type type) {
            return typeof(UnityEngine.ISerializationCallbackReceiver).IsAssignableFrom(type);
        }

        public override void OnBeforeSerialize(Type storageType, object instance) {
            ((UnityEngine.ISerializationCallbackReceiver)instance).OnBeforeSerialize();
        }

        public override void OnAfterDeserialize(Type storageType, object instance) {
            ((UnityEngine.ISerializationCallbackReceiver)instance).OnAfterDeserialize();
        }
    }
#endif

**Comment by josephsw** [comment]
Can also possibly be fixed by adding "using UnityEngine;" in the assemblies at the top of the file?

**Comment by Tulrath** [comment]
Yep, that fixes it as well.

**Comment by jacobdufault** [comment]
Please reopen if this reproduces on the latest master. At the top of `fsISerializationCallbacks.cs`, I see

```c#
#if !NO_UNITY
using UnityEngine;
#endif
```

which should be active when importing into Unity.
