### ISSUE TITLE
When using versioning, $ref refers to the old non-migrated version.

### ISSUE THREAD

**Issue by Metavirulent** [jacobdufault/fullserializer#73]
When using versioning to automatically migrate to a newer version, the serializer loads the legacy version and automatically migrates it to the newer version.

However, any $ref references will contain the original version and thus will not be migrated. This results in a mixture of migrated and non-migrated versions for the same object which will break the migration.

**Comment by jacobdufault** [comment]
Looks like we forgot to close this one out, thanks for fixing the issue in c240d14e21d48917ea057f69812ebfa627f139a2!
