### ISSUE TITLE
Building for WP8?

### ISSUE THREAD

**Issue by TinyTitanAli** [jacobdufault/fullserializer#76]
Hi,

I'm trying to build for Windows Phone 8.1 but I'm getting these errors:

    Assets\Plugins\FullSerializer\Source\Internal\fsPortableReflection.cs(53,33): error CS1503: Argument 1: cannot convert from 'System.Reflection.TypeInfo' to 'System.Type'

    Assets\Plugins\FullSerializer\Source\Internal\fsPortableReflection.cs(53,20): error CS1502: The best overloaded method match for 'FullSerializer.Internal.fsPortableReflection.GetAttribute(System.Type, System.Type)' has some invalid arguments

I looked at the docs and you mentioned we could build a dll for Windows store/phone. I opened up the "Build Files (DLL)" folder following the instructions but all I saw there was .meta files, there is no "CommonData.proj", but there was "CommonData.proj.meta"

What am I missing?

Thanks.

**Comment by jacobdufault** [comment]
Looks like it got accidentally removed during the restructuring. I'll reupload it.
