### ISSUE TITLE
Deserialization of class with no default ctor fails

### ISSUE THREAD

**Issue by jpw** [jacobdufault/fullserializer#94]
Hi there!

I've just started playing with fullserializer, so apologies if I have misunderstood or missed sth obvious.
Upon trying to deserialize a Dictionary of mine I get the following error;

```
MissingMethodException: Method not found: 'Default constructor not found...ctor() of OSM.MapWay'.
System.Activator.CreateInstance (System.Type type, Boolean nonPublic) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:368)
FullSerializer.fsMetaType.CreateInstance () (at Assets/Libraries/FullSerializer/Reflection/fsMetaType.cs:320)
Rethrow as InvalidOperationException: Unable to create instance of OSM.MapWay; there is no default constructor
FullSerializer.fsMetaType.CreateInstance () (at Assets/Libraries/FullSerializer/Reflection/fsMetaType.cs:325)
FullSerializer.Internal.fsReflectedConverter.CreateInstance (FullSerializer.fsData data, System.Type storageType) (at Assets/Libraries/FullSerializer/Converters/fsReflectedConverter.cs:90)
...

```
OSM.MapWay does indeed not have a default constructor, only parameterised ones. It does not inherit from MonoBehaviour or ScriptableObject and I'm not using any of Unity's serialization stuff -- I'm manually writing & reading JSON (generated using the example code in the README) to text files. I'm using the latest master & Unity 5.3.0f4 on OSX.

Does this mean I can't use fullserializer with data structures which include this class, or am I Doing It Wrong?  Thanks.

**Comment by jacobdufault** [comment]
This sounds like a stripping issue. Does it happen in editor or in a deployed il2cpp build?

**Comment by jpw** [comment]
Thank you for your response :)  This happens in the editor.

I am procedurally generating pretty much all my content when I hit Play. The world is defined in XML and I am trying to cache the result of an initial parsing phase. This XML parsing results in the creation of lots of these objects, which I am having trouble deserializing;
```
namespace OSM
{
	public class MapWay
	{
...
		/// <summary>
		/// Constructor extracts a Int64 Id from the supplied XElement and dereferences OSM node values to already-parsed
		/// MapNode objects.
		/// </summary>
		/// <param name="ele">An XElement with id attr and child "nd" elements.</param>
		/// <param name="nodes">A ref to all the dereferenced MapNodes.</param>
		public MapWay(XElement ele, Dictionary<ulong, MapNode> nodes)
		{
		
```
That is the only constructor in the class.  The class I am actually serializing is this;
```
		private class Container
		{
			public Dictionary <OSM.WayTypes, List<OSM.MapWay>> WaysByType;
		}
```
The resultant JSON looks like;
```
{
  "WaysByType": {
    "Waterway": [
      
    ],
    "BuildingDefault": [
      {
        "Id": 25503671,
        "Nodes": [
          {
            "Id": 3988105437,
            "UnityX": 73.58025,
            "UnityZ": 78.40903
          },
          {
            "Id": 3988105436,
            "UnityX": 73.92094,
            "UnityZ": 78.40714
          },
...
        ],
        "PartOfARelation": false,
        "Height": 0,
        "WayType": "BuildingDefault",
        "InnerWays": null
      },
...
```
...which looks correct to me.

**Comment by jpw** [comment]
After adding a parameterless constructor to the class, it appears to work!

**Comment by jacobdufault** [comment]
Oh, in the initial description I misread this

> OSM.MapWay does indeed not have a default constructor, only parameterised ones.

Depending on the build mode of Unity, you need to have a default constructor, since various Unity configurations do not support the required APIs to support deserialization without a default ctor.
