### ISSUE TITLE
Could you rearrange project structure

### ISSUE THREAD

**Issue by pointcache** [jacobdufault/fullserializer#95]
Hello due to how you arranged repository it is impossible to insert it into another as a submodule without problems.Would be perfect if it was not the whole project folder but just the code, so i can link your into mine project.

**Comment by jacobdufault** [comment]
What's the issue with the project structure? I have Full Serializer embedded inside of Full Inspector as a submodule using [sparse checkouts](http://stackoverflow.com/questions/6238590/set-git-submodule-to-shallow-clone-sparse-checkout).
