### ISSUE TITLE
Values get lost for BaseObjects on compilation 

### ISSUE THREAD

**Issue by marek-mayer** [jacobdufault/fullserializer#96]
Values set in the inspector for an object MyObject (which derives from BaseObject), that is used by a script MyScript (which derives from BaseBehaviour), disappear after an compilation (automatically by unity) of the MyObject or MyScript class (even if there were no code changes and only a whitepsace has been added to this class, the compilation is triggered).
We use Unity 5.3.4. 
The classes are: 
MyScript:
```csharp
using System.Collections.Generic;
using FullInspector;
public class FullInspectorPropertiesTests : BaseBehavior
{
    public Dictionary<string, int> StringIntDict;
    public Dictionary<int, bool> IntBoolDict;
    public Dictionary<int, List<int>> IntIntListDict;
    public FiTestObject1 TestObject1;
    public FiTestObject2 TestObject2;
}
```
MyObject 1:
```csharp
using System.Collections.Generic;
using FullInspector;
public class FiTestObject1 : BaseObject
{
    public Dictionary<int, string> IdToNameDict;
    public Dictionary<int, string> IdToNameDict2 { get; set; }
    public Dictionary<int, bool> IdToNameDict3 { get; set; }
}
```
MyObject 2:
```csharp
using System.Collections.Generic;
using FullInspector;
public class FiTestObject2 : BaseObject
{
    public Dictionary<string, string> UserNameToEmailDict;
}
```

**Comment by jacobdufault** [comment]
Thanks, I'm able to reproduce this. I'll take a look. FYI, this bug should be filed in the full inspector repro, but we can work with it here (Full Serializer doesn't know anything about BaseObject / BaseBehavior).

**Comment by jacobdufault** [comment]
Oh - `BaseObjects` rely on Unity serialization, so they need to have a `[Serializable]` annotation.

```
[Serializable]
public class FiTestObject1 : BaseObject /* ... */

[Serializable]
public class FiTestObject2 : BaseObject /* ... */
```

After applying that patch, the issue no longer reproduces locally.

**Comment by jacobdufault** [comment]
I've updated the [BaseObject documentation](https://jacobdufault.github.io/fullinspector/guide/#docs/usage?more_on_baseobject) to explicitly call out the need for the `[Serializable]` annotation.

**Comment by marek-mayer** [comment]
It works, thanks!
